### ISSUE TITLE
Renew the repository

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/comp#1]
This project started as (and still is) a fork of jaseg/python-mpv but since I need to do some pull requests on the original repo, I imported it here.

@alekcacko, @NateTheGreatt, @dark-yux, @joshuamabina, @SirBoonami, @Weznon, @CyanJDroid, @imitis, @rigrassm, @Bfgeshka and @McFkCoding, thank you for your encouragement. The current stable branch is `testing` (how irony) and I wish to have you guys checking my program again :bowing_man:

Edit: as of 2017-05-22, version 0.2.x is merged to `master`.

**Comment by plotnw** [comment]
I want to thank you for making this - I always had wanted something like this, but I never had the skill to do so. 

Thanks for making this awesome program, can't wait to see where it goes.

**Comment by McSinyx** [comment]
@Weznon Sorry for late reply and thanks for you compliment. I'm also a student and the project is not big or fine (the number of hacks, including hacky and temporary hacks is too damn high) and I really need help to continue the development. It'd be really nice if you know somebody that know some Python and is willing to dig into badly documented library (in this case, [youtube-dl](https://github.com/rg3/youtube-dl)). This is the third time I refactor comp and I'm feeling so exhausted, hence a contributor would be great. Thanks.
