### ISSUE TITLE
Bare exceptions and unused imports

### ISSUE THREAD

**Issue by cclauss** [McSinyx/comp#11]
The bare exceptions should be fixed https://travis-ci.org/McSinyx/comp/jobs/369650709#L501

https://realpython.com/the-most-diabolical-python-antipattern

**Comment by McSinyx** [comment]
I'm sorry that I totally missed this issue.  Anyway to explain some exceptions are not documented upstream and at these places there are more than one kind can be raised for the same error.  Thank you for noticing.
