### ISSUE TITLE
No libmpv on MacOS 

### ISSUE THREAD

**Issue by TrungNguyen1909** [McSinyx/comp#4]
libmpv can't be installed on MacOS by homebrew

**Comment by TrungNguyen1909** [comment]
Well, On MacOS, it's was mpv

**Comment by McSinyx** [comment]
Thanks, the documentation will be updated soon (as soon as I figure out how to install man pages to locations relative to `prefix` using `setuptools.setup`).

**Comment by McSinyx** [comment]
Documentation added in 0066d60a4e541700061b09d4ab7bab80cbab994c.

**Comment by McSinyx** [comment]
No worries, I'm just playing with the labels.
