### ISSUE TITLE
change mode hotkey & shuffle issues

### ISSUE THREAD

**Issue by gotbletu** [McSinyx/comp#8]
1) **Alt+m** not working, doesn't change modes anymore, just mutes the video
2) if i set my config to **shuffle-all**, then select a video and hit Enter it doesn't play the video i am on. It selects a random video on the playlist

**Comment by McSinyx** [comment]
I've fixed (2) but couldn't upload to PyPI yet so you may try to install the [wheel (whl) here](https://github.com/McSinyx/comp/releases/tag/0.4.5). There is also another way to keep on track with this Github repo:

```sh
git clone https://github.com/McSinyx/comp # clone it
pip3 install -e comp # this creates symlinks to the executables so you don't have to reinstall to update
git pull origin bachelor # when there is an update
```

I can't reproduce (1) however.

Edit: uploaded to PyPI now.

**Comment by gotbletu** [comment]
it still mutes the video, is there a way to rebind the Alt+m hotkey then?

**Comment by McSinyx** [comment]
Well `m` mutes the video, and did you type Alt-m on comp terminal window or mpv window? Also which emulator are you using, works fine for me on UXTerm though. You can rebind it by editing [line 519 of comp](https://github.com/McSinyx/comp/blob/0.4.5/comp#L519) or suggest another bind that works for you. I'll add support for configurable bindings in the future, but that will take some time.

**Comment by gotbletu** [comment]
oh yea works with other terminal.

im using regular **xterm**, doesnt seem to work with it, guess thats on my end
